### ISSUE TITLE
Owner receives profit from a turnstile entry

### ISSUE THREAD

**Issue by Bloodlex** [Lxmune/turnstile-renewed#1]
Hello,

I have an idea, that payments could be transferred to a person or a server account that is set as an owner of a turnstile. On my server that would go to the city budget, that is the owner of subway system. If players are also allowed to own turnstiles, they could build their own points of interests, guarded by a turnstile, and get profit from it 🙂 💰 .

Best regards,
Bloodlex

**Comment by Lxmune** [comment]
Hi !

I will implement the payment transfers (ownership of the turnstile) rather soon.
As for the players owning turnstiles, well I will need to take time on this one :wrench: 

To be added.

**Comment by Lxmune** [comment]
Added in the next update.
