### ISSUE TITLE
Translation of texts

### ISSUE THREAD

**Issue by Bloodlex** [Lxmune/turnstile-renewed#5]
Hello,

A possibility to edit sent messages in a file like messages.yml or something simillar.

Best regards,
Bloodlex

**Comment by Lxmune** [comment]
How did I completely forget about this one :joy_cat: 

To be added (soon i think)

**Comment by Bloodlex** [comment]
> How did I completely forget about this one 😹
> 
> To be added (soon i think)

Hah, sure, don't worry 🙂

**Comment by Lxmune** [comment]
Added in the next update.
